name: default
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pip
  - conda-lock
  - numpy
  - scipy
  - scikit-image
  - jupyter
  - jupyterlab
  - nodejs # needed by jupyterlab
  - jupytext
  - ipython
  - nb_conda
  - matplotlib
  - cmocean
  - cartopy
  - xarray
  - netcdf4
  - pyproj
  - dask
  - numba
  - livereload # for previewing websites/slides
  - tqdm
  - black
  - flake8
  - nox
  # Fatiando
  - pooch
  - verde
  - harmonica
  - rockhound
  - boule
  # GMT stuff
  - gmt
  - pygmt
  - fftw
  - gdal
  - ghostscript
  - libnetcdf
  - hdf5
  - zlib
  - curl
  - pcre
